site_name: LIUR DOKUMENTASI
pages:
    - Home: index.md
    - Terminologi: terminologi.md
    - Komponen: komponen.md
    - Instalasi: instalasi.md
    - User Guide: userguide.md
theme: readthedocs


